import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";
import { CartIconProvider } from "@/components/cart/CartIconContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen h-full`}
      >
        <Providers>
          <CartIconProvider>
            <Header />
            <div className="flex-1 flex flex-col overflow-y-auto h-full">
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </CartIconProvider>
        </Providers>
      </body>
    </html>
  );
}
